Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.provider "virtualbox" do |vb|
    vb.name= "sonarqube_vagrant"
    vb.gui = false
    vb.cpus = 2
    vb.memory = "2048"
  end
  
  config.vm.provision "shell" do |shell|
    shell.path = "sonarqube.sh"
  end
end