version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./deployment:/deployments
  artifactory:
    image: mattgruter/artifactory
    container_name: artifactory
    ports:
      - "8081:8080"
  sonarqube:
    image: sonarqube
    platform: linux/x86_64
    container_name: sonarqube
    ports:
      - "9000:9000"